import './assets/main.css'

import { createApp } from 'vue'
import { createPinia } from 'pinia'

import App from './App.vue'
import router from './router'
import { createI18n } from 'vue-i18n'
import auth from './plugins/auth'
import PrimeVue from 'primevue/config'
import Aura from '@primeuix/themes/aura'

const app = createApp(App)

app.use(createPinia()).use(auth)
app.use(
  createI18n({
    legacy: false,
    locale: 'en',
    fallbackLocale: 'en',
    messages: {
      en: {
        messages: {
          general: {
            viewAll: 'View All',
            share: 'Share',
            date: 'Date',
            langCode: 'en-US',
            status: 'Status',
            paymentMethod: 'Payment Method',
            clearFilters: 'Clear Filters',
            up: 'Up',
            please: 'Please',
            shipping: 'Shipping',
            shippingDetails: 'Shipping Details',
            shippingSelect: 'Select Shipping Method',
            tax: 'Tax',
            myDetails: 'My Details',
            home: 'Home',
            allProducts: 'Products',
            product: 'Product',
            contact: 'Contact',
            menu: 'Menu',
            color: 'Color',
            choose: 'Choose | Choose',
            basedOn: 'Based on',
            apply: 'Apply',
            latest: 'Latest',
            alphabetically: 'Alphabetically',
            clear: 'Clear',
            optional: 'Optional',
            downloads: 'Downloads',
            download: 'Download',
            goHome: 'Go Home',
            newsletter: 'Newsletter',
            customerService: 'Customer Service',
            processing: 'Processing',
            readOnly: 'Readonly',
          },
          account: {
            changePassword: 'Change Password',
            currentPassword: 'Current Password',
            password: 'Password',
            newPassword: 'New Password',
            confirmNewPassword: 'Confirm New Password',
            updatePassword: 'Update Password',
            forgotPassword: 'Forgot password?',
            orContinueWithEmail: 'or continue with email',
            username: 'Username',
            emailOrUsername: 'Email or Username',
            login: 'Log In',
            logout: 'Logout',
            backToLogin: 'Back to Login',
            enterEmailOrUsernameForReset: 'Please enter your email address or username and we will send you a link to reset your password.',
            ifRegistered: 'If your email address is registered with us, you will receive an email with a link to reset your password.',
            requestNewLink: 'Please request a new link',
            resetPassword: 'Reset password',
            sendPasswordResetEmail: 'Send Password Reset Email',
            register: 'Register',
            accountRegister: 'Sign up',
            accountLogin: 'log in',
            noAccount: "Don't have an account?",
            hasAccount: 'Already have an account?',
            accountCreated: 'Your account has been created.',
            myAccount: 'My Account',
            loginToAccount: 'Log in to your account',
            loggingIn: 'Logging you in...',
            personalInfo: 'Personal Information',
            updating: 'Updating',
            updateDetails: 'Update Details',
            updateSuccess: 'Updated successfully',
            failed: 'Failed to update',
          },
          shop: {
            shopByCategory: 'Shop by Category',
            popularProducts: 'Popular Products',
            availability: 'Availability',
            inStock: 'In Stock',
            outOfStock: 'Out of Stock',
            onBackorder: 'On Backorder',
            sku: 'SKU',
            price: 'Price',
            category: 'Category | Categories',
            youMayLike: 'You May Also Like',
            wishlist: 'Wishlist',
            wishlistRemove: 'Remove from Wishlist',
            wishlistAdd: 'Add to Wishlist',
            wishlistNoItems: 'You have no items in your wishlist',
            addToCart: 'Add to Cart',
            adding: 'Adding...',
            productDescription: 'Description',
            productImage: 'Product Image',
            productBestSellers: 'Best Sellers',
            newArrivals: 'New Arrivals',
            onSale: 'On Sale',
            reviews: 'Reviews',
            customerReviews: 'Customer Reviews',
            noReviews: 'No reviews yet.',
            writeReview: 'Write a Review',
            close: 'Close',
            rateReview: 'How would you rate your experience with this product? We strive for a 5 star experience',
            rateContent: 'How was your experience?',
            rateEmail: 'Your email',
            submit: 'Submit',
            order: 'Order | Orders',
            orderSummary: 'Order Summary',
            orderReceived: 'Order Received',
            orderNote: 'Order Note | Order Notes',
            orderNotePlaceholder: 'Notes about your order, e.g. special notes for delivery.',
            orderThanks: 'Thank you for your order. We will send you an email with the order details.',
            orderHistory: 'Order History',
            placeOrder: 'Place Order',
            total: 'Total',
            subtotal: 'Subtotal',
            rating: 'Rating | Ratings',
            cart: 'Cart',
            cartEmpty: 'Your cart is empty.',
            addProductsInYourCart: 'Please, add some products to your cart.',
            browseOurProducts: 'Browse our products',
            checkout: 'Checkout',
            checkoutButton: 'Checkout',
            discount: 'Discount',
            giftCards: 'Gift Cards',
            searchProducts: 'Search Products...',
            couponCode: 'Coupon Code',
            downloadsRemaining: 'Downloads remaining',
            expires: 'Expires',
            productNotFound: 'Product not found',
            productResultCount: {
              showing: 'Showing',
              to: 'to',
              of: 'of',
            },
            noProductsFound: {
              title: 'No products found',
              subText: "Try adjusting your search or filter to find what you're looking for.",
              clearFiltersAndSearch: 'Clear all filters and search',
            },
          },
          billing: {
            billing: 'Billing',
            billingDetails: 'Billing Details',
            firstName: 'First Name',
            lastName: 'Last Name',
            address1: 'Address 1',
            address2: 'Address 2',
            city: 'City',
            state: 'State',
            zip: 'Postal Code / ZIP',
            country: 'Country',
            countryCode: 'Country Code',
            phone: 'Phone',
            email: 'Email',
            paymentOptions: 'Payment Options',
            creditCard: 'Credit Card',
            cashOnDelivery: 'Cash on Delivery',
            differentAddress: 'Ship to a different address?',
          },
          error: {
            invalidUsername: 'No account found with that username. Sign up for a new account.',
            incorrectPassword: 'Incorrect password. Please try again.',
            passwordMismatch: 'Passwords do not match. Please try again.',
            invalidPasswordResetLink: 'Password reset link is invalid.',
            general: 'Something went wrong',
            noOrder: 'We could not find your order. Please try again later.',
          },
          identity: {
            signIn: 'Sign In',
            signUp: 'Sign Up',
          },
        },
      },
      de: {
        messages: {
          general: {
            viewAll: 'Alle anzeigen',
            share: 'Teilen',
            date: 'Datum',
            langCode: 'de-DE',
            status: 'Status',
            paymentMethod: 'Zahlungsmethode',
            clearFilters: 'Filter löschen',
            up: 'aufwärts',
            please: 'Bitte',
            shipping: 'Versand',
            shippingDetails: 'Versanddetails',
            shippingSelect: 'Versandart auswählen',
            tax: 'MwSt.',
            myDetails: 'Meine Details',
            home: 'Startseite',
            allProducts: 'Alle Produkte',
            product: 'Produkt',
            contact: 'Kontakt',
            menu: 'Menü',
            color: 'Farbe',
            choose: 'Wähle | Wählen',
            basedOn: 'Basierend auf',
            apply: 'Anwenden',
            latest: 'Neueste',
            alphabetically: 'Alphabetisch',
            clear: 'Löschen',
            optional: 'Optional',
            downloads: 'Downloads',
            download: 'Download',
            goHome: 'Zur Startseite',
            newsletter: 'Newsletter',
            customerService: 'Kundenservice',
            processing: 'Wird verarbeitet',
            readOnly: 'Nur-Lesen',
          },
          account: {
            changePassword: 'Passwort ändern',
            currentPassword: 'Aktuelles Passwort',
            password: 'Passwort',
            newPassword: 'Neues Passwort',
            confirmNewPassword: 'Neues Passwort bestätigen',
            updatePassword: 'Passwort aktualisieren',
            forgotPassword: 'Passwort vergessen?',
            username: 'Benutzername',
            emailOrUsername: 'E-Mail oder Benutzername',
            login: 'Anmelden',
            logout: 'Logout',
            backToLogin: 'Zurück zum Login',
            enterEmailOrUsernameForReset:
              'Bitte geben Sie Ihre E-Mail-Adresse oder Ihren Benutzernamen ein, und wir senden Ihnen einen Link zum Zurücksetzen Ihres Passworts.',
            ifRegistered:
              'Wenn Ihre E-Mail-Adresse bei uns registriert ist, erhalten Sie eine E-Mail mit einem Link zum Zurücksetzen Ihres Passworts.',
            requestNewLink: 'Bitte fordern Sie einen neuen Link an',
            resetPassword: 'Passwort zurücksetzen',
            sendPasswordResetEmail: 'Passwort-zurücksetzen-E-Mail senden',
            register: 'Registrieren',
            accountRegister: 'registrieren',
            accountLogin: 'einloggen',
            noAccount: 'Noch kein Konto?',
            hasAccount: 'Haben Sie bereits ein Konto?',
            accountCreated: 'Ihr Konto wurde erstellt.',
            myAccount: 'Mein Konto',
            loginToAccount: 'Melden Sie sich mit Ihrem Konto an',
            loggingIn: 'Anmeldung...',
            personalInfo: 'Persönliche Informationen',
            updating: 'Aktualisierung',
            updateDetails: 'Details aktualisieren',
            updateSuccess: 'Erfolgreich aktualisiert',
            failed: 'Aktualisierung fehlgeschlagen',
          },
          shop: {
            shopByCategory: 'Kategorien',
            popularProducts: 'Beliebte Produkte',
            availability: 'Verfügbarkeit',
            inStock: 'auf Lager',
            outOfStock: 'ausverkauft',
            onBackorder: 'Nachbestellung',
            sku: 'SKU',
            price: 'Preis',
            category: 'Kategorie | Kategorien',
            youMayLike: 'Könnte Ihnen auch gefallen',
            wishlist: 'Wunschliste',
            wishlistRemove: 'Von Wunschliste entfernen',
            wishlistAdd: 'Zur Wunschliste hinzufügen',
            wishlistNoItems: 'Ihre Wunschliste ist leer.',
            addToCart: 'In den Warenkorb',
            adding: 'Wird hinzugefügt...',
            productDescription: 'Beschreibung',
            productImage: 'Produktbild',
            productBestSellers: 'Bestseller',
            newArrivals: 'Neuheiten',
            onSale: 'Im Angebot',
            reviews: 'Bewertungen',
            customerReviews: 'Kundenbewertungen',
            noReviews: 'Noch keine Bewertungen',
            writeReview: 'Bewertung schreiben',
            close: 'Schließen',
            rateReview: 'Wie würden Sie dieses Produkt bewerten?',
            rateContent: 'Ihre Bewertung',
            rateEmail: 'Ihre E-Mail-Adresse',
            submit: 'Senden',
            order: 'Bestellung | Bestellungen',
            orderSummary: 'Bestellübersicht',
            orderReceived: 'Vielen Dank für Ihre Bestellung. Wir senden Ihnen eine E-Mail mit den Bestelldetails zu.',
            orderNote: 'Bestellnotiz | Bestellnotizen',
            orderNotePlaceholder: 'Nachricht zu Ihrer Bestellung, zum Beispiel zur Lieferung.',
            orderThanks: 'Vielen Dank für Ihre Bestellung. Wir senden Ihnen eine E-Mail mit den Bestelldetails zu.',
            orderHistory: 'Bestellverlauf',
            placeOrder: 'Bestellung aufgeben',
            total: 'Gesamt',
            subtotal: 'Zwischensumme',
            rating: 'Bewertung | Bewertungen',
            cart: 'Warenkorb',
            cartEmpty: 'Ihr Warenkorb ist leer',
            addProductsInYourCart: 'Bitte fügen Sie einige Produkte in Ihren Warenkorb hinzu.',
            browseOurProducts: 'Stöbern Sie in unseren Produkten',
            checkout: 'Kasse',
            checkoutButton: 'jetzt bezahlen',
            discount: 'Rabatt',
            giftCards: 'Geschenkkarten',
            searchProducts: 'Produkte suchen...',
            couponCode: 'Gutscheincode',
            downloadsRemaining: 'Verbleibende Downloads',
            expires: 'Läuft ab',
            productNotFound: 'Produkt nicht gefunden',
            productResultCount: {
              showing: 'Anzeige',
              to: 'bis',
              of: 'von',
            },
            noProductsFound: {
              title: 'Keine Produkte gefunden',
              subText: 'Versuchen Sie, Ihre Suche oder Filter anzupassen, um das zu finden, was Sie suchen.',
              clearFiltersAndSearch: 'Alle Filter und die Suche zurücksetzen',
            },
          },
          billing: {
            billing: 'Rechnung',
            billingDetails: 'Rechnungsadresse',
            firstName: 'Vorname',
            lastName: 'Nachname',
            address1: 'Addresse',
            address2: 'Addresszeile 2',
            city: 'Ort',
            state: 'State',
            zip: 'Postleitzahl / ZIP',
            country: 'Land',
            countryCode: 'Ländercode',
            phone: 'Telefon',
            email: 'E-Mail',
            paymentOptions: 'Zahlungsoptionen',
            creditCard: 'Kreditkarte',
            cashOnDelivery: 'Nachname',
            differentAddress: 'Abweichende Lieferadresse?',
          },
          error: {
            invalidUsername: 'Ungültiger Benutzername. Bitte registrieren Sie sich.',
            invalidPassword: 'Ungültiges Passwort. Bitte versuchen Sie es erneut.',
            passwordMismatch: 'Die Passwörter stimmen nicht überein. Bitte versuche es erneut.',
            invalidPasswordResetLink: 'Der Passwort-Reset-Link ist ungültig.',
            general: 'Etwas ist schief gelaufen',
            noOrder: 'Wir konnten Ihre Bestellung nicht finden. Bitte versuchen Sie es später noch einmal.',
          },
          identity: {
            signIn: 'Anmelden',
            signUp: 'Registrieren',
          },
        },
      },
    },
  }),
)
app.use(router)
app.use(PrimeVue, {
  theme: {
    preset: Aura,
    options: {
      cssLayer: {
        name: 'primevue',
        order: 'theme, base, primevue',
      },
    },
  },
})

app.config.errorHandler = (err, vm, info) => {
  console.error('Error:', err)
  console.error('Vue instance:', vm)
  console.error('Info:', info)
}

app.config.warnHandler = (msg, vm, trace) => {
  console.warn('Warning:', msg)
  console.warn('Vue instance:', vm)
  console.warn('Trace:', trace)
}

app.config.performance = true

app.mount('#app')
