global:
  scrape_interval: 1s

scrape_configs:
  - job_name: 'catalog'
    static_configs:
      - targets: ['catalog.api:5103']
  - job_name: 'ordering'
    static_configs:
      - targets: ['ordering.api:5105']