apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: catalog-database-pvc
  namespace: thesis
spec:
  # ingressClassName: ingress-service
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi