apiVersion: v1
kind: Secret
metadata:
  name: catalog-postgres-secret
  namespace: thesis
type: Opaque
data:
  POSTGRES_USER: cG9zdGdyZXM=
  POSTGRES_PASSWORD: cG9zdGdyZXM=
  POSTGRES_DB: Y2F0YWxvZw==