apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc
  namespace: modularmonolith
spec:
  ingressClassName: ingress-service
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi