apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: modularmonolith
type: Opaque
data:
  POSTGRES_USER: cG9zdGdyZXM=
  POSTGRES_PASSWORD: cG9zdGdyZXM=
  POSTGRES_DB: bW9kdWxhcm1vbm9saXRo