apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp-server-deployment
  labels:
    app: webapp-server
  namespace: thesis
spec:
  # ingressClassName: web-ingress
  replicas: 1
  selector:
    matchLabels:
      app: webapp-server
  template:
    metadata:
      labels:
        app: webapp-server
    spec:
      containers:
        - name: webapp.server
          image: turalhasanov/thesis/webappserver:dev
          imagePullPolicy: Always
          resources:
            limits:
              memory: "512Mi"
              cpu: "500m"
            requests:
              memory: "256Mi"
              cpu: "250m"
          ports:
            - containerPort: 5113
          readinessProbe:
            httpGet:
              path: /health
              port: 5113
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /health
              port: 5113
            initialDelaySeconds: 15
            periodSeconds: 20
          securityContext:
            allowPrivilegeEscalation: false
            privileged: false
      securityContext:
        runAsUser: 1001
        runAsGroup: 1001
        runAsNonRoot: true

---
apiVersion: v1
kind: Service
metadata:
  name: webapp-server-service
  labels:
    app: webapp-server
  namespace: thesis
spec:
  selector:
    app: webapp-server
  ports:
  - name: http
    protocol: TCP
    port: 5113
    targetPort: 5113
  type: LoadBalancer
---
# apiVersion: networking.k8s.io/v1
# kind: Ingress
# metadata:
#   name: webapp-server-ingress
#   namespace: thesis
#   annotations:
#     kubernetes.io/ingress.class: nginx
#     nginx.ingress.kubernetes.io/use-regex: 'true'
# spec:
#   rules:
#   - host: modularmonolith.local
#     http:
#       paths:
#       - path: /?(.*)
#         pathType: Prefix
#         backend:
#           service:
#             name: web-service
#             port:
#               number: 80