global using Ardalis.Result;
global using MediatR;
global using Microsoft.EntityFrameworkCore;
global using Microsoft.Extensions.DependencyInjection;
global using Microsoft.Extensions.DependencyInjection.Extensions;
global using Webhooks.Contracts.IntegrationEvents;
global using Webhooks.Core.WebhookAggregate;
global using Webhooks.Infrastructure.Data;
global using Webhooks.Infrastructure.Repositories;
