services:
  webapp:
    image: ${DOCKER_REGISTRY-}webapp
    container_name: webapp
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 5002:80
    networks:
      - thesis-net
    environment:
      VITE_API_URI: 'https://webapp.bff:5113'

  nginx:
    image: nginx:alpine
    container_name: nginx-app
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 80:80
    depends_on:
      - webapp
    networks:
      - thesis-net

networks:
  thesis-net:
    driver: bridge
