name: client-ci

on:
  push:
    branches: ["main"]
    paths-ignore:
      - ".github/workflows/main-ci.yml"
      - "**/*.md"
  pull_request:
    branches: ["main"]
    paths-ignore:
      - ".github/workflows/main-ci.yml"
      - "**/*.md"

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest]
        node: [22]

    steps:
      - name: Checkout Web App
        uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v4

      - name: Install node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}
          cache: pnpm

      - name: Install dependencies
        run: pnpm install

      - name: Lint
        run: pnpm run lint

      - name: Typecheck
        run: pnpm run typecheck
